### ISSUE TITLE
Theme broken after update

### ISSUE THREAD

**Issue by AmetAlvirde** [sainnhe/vim-color-forest-night#1]
Using neovim 0.3.7-2, after updating the theme, throws this error at startup:

```
Error detected while processing ~/.local/share/nvim/plugged/vim-color-forest-night/colors/forest-night.vim:
line   45:
E121: Undefined variable: g:spring_night_high_contrast
E15: Invalid expression: g:spring_night_high_contrast ? '#213243' : '#3a4b5c'
line   67:
E121: Undefined variable: s:bgweaker_gui
Press ENTER or type command to continue
```
After pressing enter, appearently it works just fine, but I really hope it can be fixed. I love your theme, but cannot use it with that annoying message every startup :(

**Comment by sainnhe** [comment]
Thanks for pointing this out, I should be more careful when merging patches from spring-night.
It should be fixed now.
