### ISSUE TITLE
Template code optimizations

### ISSUE THREAD

**Issue by lifepillar** [sainnhe/vim-color-forest-night#11]
Hi, Colortemplate's author here. I'd like to suggest a couple of improvements to your template's code. Starting with v2, Colortemplate (kind of) detects italics automatically, so, in general, you don't need an option for that. If you still want to provide an option (e.g., to let the user disable italics even when it is supported), the idiomatic way of doing it is to override the value of `s:italics`, i.e., at the beginning of your template (just after the metadata) add this line:

```
#let s:italics = get(g:, '@optionprefix_use_italic', 1) && s:italics
```

Then, you don't need to do anything special with your highlight group definitions: : just define the highlight groups as if italics is available. This is what I do, for instance, in [Solarized 8](https://github.com/lifepillar/vim-solarized8/blob/master/templates/_global.colortemplate).

Incidentally, the option prefix key should be omitted or set to something unique to your color scheme: `dark` is too generic.

The other thing is that the `_bw` template has been updated to use a new special `omit` keyword, which avoids the need to define an unused color. See the Colortemplate project for the details.

Nice color schemes!

**Comment by sainnhe** [comment]
Thank you very much! I've updated my codes.
Btw, colortemplate is a very awesome plugin, it's very easy to build a high performance color scheme using this (I'm shocked by the loading time of this color scheme)
Thanks again for developing this plugin!
