### ISSUE TITLE
How do I load the lightline theme via vim-plug?

### ISSUE THREAD

**Issue by martisj** [sainnhe/vim-color-forest-night#12]
Is it possible to load the lightline scheme without having to manually copy the `autoload/lightline` files to `~/.vim/autoload`?

**Comment by martisj** [comment]
Ok that was a dooby, i spelled the lightline colorscheme wrong!!!  😂
May I suggest a change in the lightline theme name to be `forest-night` instead of `forest_night`

**Comment by sainnhe** [comment]
I've tried `forest-night`, but this syntax is wrong, you can only use underscores.

**Comment by martisj** [comment]
> I've tried `forest-night`, but this syntax is illegal, you can only use underscores.

Gotcha! Thanks for the reply
