### ISSUE TITLE
Colors within :map are barely readable

### ISSUE THREAD

**Issue by lgalke** [sainnhe/vim-color-forest-night#13]
When I call `:map` or alike the colors of special symbols like `<Space>` are very dark on dark background, and thus, barely readable. Unfortunately, I could not find out which Highlight group is actually used there.

## with termguicolors
![image](https://user-images.githubusercontent.com/3439126/61882724-5228b500-aef9-11e9-8f20-0f1b68a9bb6e.png)

## with 256 colors (notermguicolors)
![image](https://user-images.githubusercontent.com/3439126/61882842-90be6f80-aef9-11e9-80ac-e34f998caf66.png)

**Comment by lgalke** [comment]
The highlight group is `SpecialKey`.

**Comment by sainnhe** [comment]
Thanks for reminding, I've adjusted `SpecialKey`. You can update this color scheme and get it a try.

**Comment by lgalke** [comment]
Thank you for the quick fix. The theme is very pleasant to the eye, I appreciate it.
