### ISSUE TITLE
What linux distro are you using?

### ISSUE THREAD

**Issue by cata0309** [sainnhe/vim-color-forest-night#14]
Hello ! I discovered your post on r/unixporn and I really love this theme and I was wonderinf if you can share some info about your linux distro, font config,hinting, antialising anything that made that text to look so good, I have been trying for ages to acomplish that.
If you can, please share your fontconfig file

**Comment by sainnhe** [comment]
- OS: Arch Linux
- Terminal Emulator: Tilix
- Font: FuraCode Nerd Font Mono

I don't have any font config yet, here are my [dotfiles](https://github.com/sainnhe/dotfiles).

For status line configuration, I wrote a gist to explain it: [gist](https://gist.github.com/sainnhe/b8240bc047313fd6185bb8052df5a8fb)

**Comment by cata0309** [comment]
So how is the text rendering so sharp in your linux distro ? Is that the default behaviour?

**Comment by sainnhe** [comment]
Oh, that's because I'm using surface device, the dpi is very high.

**Comment by cata0309** [comment]
Thank you !

**Comment by cata0309** [comment]
Can you share the name of your surface machine and some info about it?

**Comment by sainnhe** [comment]
[Surface Pro 5](https://www.microsoft.com/en-us/p/surface-pro-5th-gen/8nkt9wttrbjk?activetab=pivot:overviewtab)

To be honest, in my mind, the dpi of any surface device is very high.

**Comment by cata0309** [comment]
That's good, I will check them out in the future
