### ISSUE TITLE
Feature: Matching Parentheses?

### ISSUE THREAD

**Issue by stefanhige** [sainnhe/vim-color-forest-night#15]
I really like your colorscheme, but the default "bold" parentheses marking
`  hi MatchParen guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold`
is barely visible. How about changing `ctermbg` a little bit?

**Comment by sainnhe** [comment]
I've adjusted it, you can update this color scheme and get it a try.
