### ISSUE TITLE
config for lightline

### ISSUE THREAD

**Issue by DanielAndreasen** [sainnhe/vim-color-forest-night#2]
Okay, I know this is not the lightline repo, but your setup looks so sleek!
I've been looking for way too long now for the right unicodes to do the same thing (the forward and backward slash) for the separator and subseparator.
So, can you please share your config for lightline? :)

Btw, forest-night is now my default colorscheme.

**Comment by sainnhe** [comment]
It depends on these plugins
```vim
Plug 'itchyny/lightline.vim'
Plug 'sainnhe/artify.vim'
Plug 'itchyny/vim-gitbranch'
Plug 'macthecadillac/lightline-gitdiff'
Plug 'maximbaz/lightline-ale'
Plug 'sinetoami/lightline-neomake'
Plug 'Palpatineli/lightline-lsc-nvim'
```
This is the configuration: [dotfiles](https://github.com/sainnhe/dotfiles/blob/a1c0066dc0cdf972d00c4bd464a93513bf31d055/.config/nvim/init.vim#L1002-L1216)
Thanks for your support :)

**Comment by DanielAndreasen** [comment]
That's an impressive vimrc. Thanks for the help :)

**Comment by DanielAndreasen** [comment]
In hope you can still help. It looks like this, but I was hoping the separator would look more like yours. Any good ideas here?
![image](https://user-images.githubusercontent.com/4519017/59050910-e5475600-888b-11e9-8782-735f2f3bdb5c.png)

**Comment by sainnhe** [comment]
The display of nerdfont can be affected by many factors, including terminal emulator type, font type, font size, zoom, etc.

Personally, I use tilix as terminal emulator, FiraCode Mono Nerd Font Mono as font type, 11 as font size, 2x zoom on my surface pro 2017.

You can adjust it yourself and choose a configuration that suits you.

**Comment by sainnhe** [comment]
I've rewritten this color scheme using vim-colortemplate, you can update this plugin and check out new look.

Btw, looks like you didn't enable termguicolors, you can set this option to get better display.

**Comment by sainnhe** [comment]
I've create a gist to describe this configuration, you can take a look if you are interested: [gist](https://gist.github.com/sainnhe/b8240bc047313fd6185bb8052df5a8fb)

**Comment by DanielAndreasen** [comment]
Thanks for the suggestions (and the gist). Will have a look at it later :)

**Comment by sainnhe** [comment]
closed
