### ISSUE TITLE
Assignment of lightline colorscheme does now work

### ISSUE THREAD

**Issue by FuzzyAzurik** [sainnhe/vim-color-forest-night#3]
When entering the lightline colorscheme as specified by the README.md
```vim 
let g:lightline.colorscheme = 'forest_night'
```
I get the following error: "E121 Undefined variable: g:lightline"

This can be resolved by either:
```vim
let g:lightline = {}
let g:lightline.colorscheme = 'forest_night'
```
or 
```vim 
let g:lightline = {'colorscheme' : 'forest_night'}
```

**Comment by sainnhe** [comment]
Thanks for pointing this out, I've fixed it in README.

**Comment by FuzzyAzurik** [comment]
Readme has been updated, closing issue.
