### ISSUE TITLE
color scheme for st or other terminal emulators

### ISSUE THREAD

**Issue by ekomizer** [sainnhe/vim-color-forest-night#5]
It would be nice to have the terminal blended with the same colors.

**Comment by sainnhe** [comment]
Yeah, that is what I plan to do recently. I finished tilix + i3 + polybar yesterday, looks pretty nice
![2019-06-14 14-12-41屏幕截图](https://user-images.githubusercontent.com/37491630/59487306-d32e6e80-8eae-11e9-9a09-922490d6a61b.png)

So far, I plan to port it to tilix, alacritty, kitty, hyper, tmux, zsh(powerlevel10k+fast syntax highlight), rofi. However, my device is surface, I don't have a mac, so I'm unable to port it to iterm2.

**Comment by sainnhe** [comment]
I've created a new repo: [sainnhe/forest-night-theme](https://github.com/sainnhe/forest-night-theme)
If you guys are interested in port this color scheme to other terminal emulators, you can open a PR with color scheme files and a readme, or simply a readme file with a link to your own repo.

**Comment by sainnhe** [comment]
I decided to delete sainnhe/forest-night-theme because I think it is unnecessary to open a separate repo for terminal color schemes.

**Comment by ekomizer** [comment]
Cool. But I suggest that you also rename the repo into just the name or the color scheme (`forest-night` or `forest-night-theme`) because it now supports theme-ing other things.

**Comment by sainnhe** [comment]
Thanks for your suggestion, but renaming this repo means many of people have to change installation command in their vimrc. Changing repository information might be better.

**Comment by sainnhe** [comment]
@lieuxnoir Hi, I have separated the theme you made.

If you are still willing to maintain it, you can create a gist or repo and update the link in master branch of this repository.

[RELATED_PROJECTS.md](https://github.com/sainnhe/vim-color-forest-night/blob/master/RELATED_PROJECTS.md)
